### ISSUE TITLE
Avoid target words that differ from many other words by just one letter.

### ISSUE THREAD

**Issue by Plethodons** [lynn/hello-wordl#33]
The only games I have lost are the ones where there are many common words that differ from the target word by one letter. Example: hills, bills, tills, rills, gills, fills, pills, kills, mills, sills, wills
Not quite as bad example: blues, flues, slues, clues, glues
This does not seem to happen in Wordle, presumably because target words are limited to avoid this problem.

**Comment by lynn** [comment]
Hmm, Wordle's list of target words doesn't _not_ have this problem:

```
>>> ends.most_common(7)
[('ight', 9), ('ound', 8), ('ower', 7), ('atch', 7), ('atty', 6), ('aunt', 6), ('aste', 6)]
>>> [w for w in ws if w.endswith('ight')]
['light', 'night', 'might', 'eight', 'wight', 'sight', 'fight', 'right', 'tight']
```

If your first guess is `patch`, and you get the `atch` all green but `p` is grey, you shouldn't then start guessing `watch, hatch, latch, match` next. Instead, you can eliminate all of these consonants in one guess with `whelm`! (This is what makes "Hard Mode" truly hard, instead of simply an appealing strategy.)

In any case, I am pushing out a change just now that gets rid of plurals, so there shouldn't be any more quite as enormous groups as `_ills` 👍

**Comment by Plethodons** [comment]
I guess I just haven’t happened to run into it with Wordle yet. Good strategy point. I tend to use “hard mode” without even selecting it — for some reason, it feels like cheating not to, but that’s just me. Getting rid of plurals should help. Thanks.
