### ISSUE TITLE
Slider for number of guesses

### ISSUE THREAD

**Issue by GarlickWitch** [lynn/hello-wordl#4]
Would it be possible to add a slider for number of guesses as well? So you could design a game with 4-word letters and 8 guesses, for example.

**Comment by lynn** [comment]
Currently, I have mysterious reasons:tm: for not wanting to add this slider.

They boil down to something like: if there are too many "modes" to play in (say 8×8 = 64 with two sliders, instead of 8), the social game experience becomes scattered. That is, "11-letter mode" becomes fractured into "11-letter mode with 3 guesses, 11-letter mode with 4 guesses, 11-letter mode with 5 guesses", … each of which has fewer players.

As-is, I like the idea that there are fewer modes, with more people playing them; and I think that 6 is a really good sweet spot, and I myself haven't really wanted to adjust it.
