### ISSUE TITLE
Hard mode doesn't detect letter in wrong position

### ISSUE THREAD

**Issue by carlmanaster** [lynn/hello-wordl#49]
![Screenshot_20220120-212147_Chrome](https://user-images.githubusercontent.com/1261137/150470960-02026374-6035-491a-93d3-68f8d868bdb0.jpg)
I was hoping hard mode would protect me from mistakes like this,.  I already knew that "A" couldn't be the third letter, but it let me put it there again.

**Comment by JohnHKoh** [comment]
The original Wordle game seems to also only validates correct letters in correct positions (green letters).

![image](https://user-images.githubusercontent.com/6465531/150474256-cb6d9308-048f-4efe-83f5-8147b7578d0f.png)

**Comment by lynn** [comment]
Wordle's hard mode enforces that yellows be used in subsequent guesses, but not that they actually be moved elsewhere; and it enforces greens to stay in the same spot. Someone on Twitter asked for an "ultra hard mode" that enforces yellows to move away and grays to not be reused. 🤔 

I don't totally see the point, because these are easy rules to self-enforce while also eliminating some of the more strategic aspects of the game. I only ported Hard Mode because Wordle has it and people might want to practice with it.

**Comment by carlmanaster** [comment]
OK, thanks.  For the record, I agree with the request for UHM, because I am using HM to catch my mistakes as a player who intends every guess to be viable.

**Comment by lynn** [comment]
Ultra Hard mode has been added 🚀

**Comment by carlmanaster** [comment]
Wow!  Thanks!  I appreciate the follow up.
