### ISSUE TITLE
Feature request: Adding game number query string value to URL

### ISSUE THREAD

**Issue by craigthings** [lynn/hello-wordl#64]
I love the seeded random puzzles. Sometimes I come across a uniquely interesting and difficult puzzle that I want to share with friends, but the unique puzzle is on game 5 or something, so when I share the puzzle with them they can't go directly to the puzzle I was trying to solve. It would be super great just to have the game number saved in the URL so I could share it! 

Thank you for this great extended version of Wordle. Endless Wordles has helped me go from terrible to middlingly average!

**Comment by dskunkler** [comment]
There is currently a 'Challenge a friend to this word' button which should seed the url with that current word. If that isn't working, can you give some reproduceable steps?

**Comment by SystemDisc** [comment]
@dskunkler If someone sends you a challenge link, you see that in the URL while you play. If you go to the site directly or follow a challenge link, after you solve the puzzle or give up, the buttons below show up for sending a challenge link or an emoji pattern with a challenge link. If you hit enter to continue playing, those buttons go away and the query string in the URL disappears.

At that point, you cannot share your current challenge unless you enter a valid word first, then give up - or, continue until you run out of turns or solve the puzzle. To me, this is very frustrating. What if I want to play with someone else is real-time or near-real-time? My girlfriend and I like playing together and we live together, so what I've been doing is covering up the screen (because it reveals the answer), entering *my* first word, clicking give up, getting the link, going to that link (now I can uncover the screen), giving her the link, entering my first word again, and continuing from there while we both solve the challenge.

**Comment by SystemDisc** [comment]
Oh, that's hilarious. I just realized the challenge link is just a base64 encoded version of the word... So, there's no storing anything in any database. Just plop the challenge link (`?challenge=Zm9yY2U`) at the top of the page for random games, and for the today games, use a link like this `?seed=20220130&game=5`.

**Comment by dskunkler** [comment]
@lynn Was the intention of not having the share link during gameplay for mobile or something? Seems like we could make the share link available during play but reserve the share result until after its finished.

**Comment by SystemDisc** [comment]
If you are ok with showing the shareable link at all times, I wouldn't mind submitting a PR.

**Comment by lynn** [comment]
I really like the ideas of:

* A regular "share" link being available even before the game is finished. (I just couldn't really think of the use-case for this, but I see it now!)
* Share links becoming like `?seed=20220130&length=5&game=3` in "Today's" mode – so that even when you're a few games deep, someone can easily join you on your seeded adventure.
* Maybe also making the location URL look like that using `history.replaceState`, so that copying it will work too.

**Comment by SystemDisc** [comment]
Yayyyy! This would be a super awesome addition for me - especially if it also works for random games and not just in the today mode. Thank you!!!

**Comment by SystemDisc** [comment]
Thanks, @lynn! Perfect implementation
