### ISSUE TITLE
Feature request: "Today's" word changes according to local time zone

### ISSUE THREAD

**Issue by alluringmoon31** [lynn/hello-wordl#91]
I've noticed that the seed of the day does not changing according to my local time zone, but instead according to a fixed one (GMT-0?).

I'd like to request that the local user time zone is automatically identified and used as a basis for when "Today's" link directs to the seed of the next day. A secondary solution would be to be able to set the time zone manually.

Thank you for the awesome project!

**Comment by lynn** [comment]
Maybe I just have too many international connections, but I find it very _weird_ that Wordle works this way: my Japanese friends are basically always one Wordle ahead of my PNW friends. I guess local time is the expected behavior though, since Wordle works that way, and in hello wordl you can just tweak the URL to play yesterday's/tomorrow's game. So I think I will merge #93 :)

**Comment by pauld-io** [comment]
I'm not sure I like this change request (to make the behaviour the same as Wordle).  I live in NZ, and share my results with family all over the world including the West Coast of the USA - which is almost a whole day behind.  Which means they don't get to do the same puzzle and share it until the next day - by which time I have forgotten what I did the previous day.  
I like the idea that for a given 24-hour period, *everybody* in the world is doing the same puzzle.  They may try it at a different time during their day or night, but when they share it, they know that the other person has access to the same puzzle.  
Not sure what others think.  If you operate only within one country this is not an issue, but when you share across the world, I think the original behaviour of HelloWordl is better than that of Wordle.  
If you are going to pick one time zone as the standard, it might as well be Zulu time (GMT), since half the world is ahead of Zulu (like me), and half is behind (like the USA).

**Comment by pauld-io** [comment]
Incidentally, I like the fact that when you share your results, it shows the date (in the URL).  Perhaps this could be made more obvious.
