### ISSUE TITLE
TAKKY accepted - British slang (sorry)

### ISSUE THREAD

**Issue by ep-on-socials** [lynn/hello-wordl#94]
Game [dGFsbHk](https://hellowordl.net/?challenge=dGFsbHk) accepted `TAKKY` -- I meant to type `TALLY`. I laughed but I also looked it up and it seems like British slang which you said you've tried to filter and `TAKKY` isn't on Norvig's list at all so I logged into the dusty'ol'github and raised an issue for you! Thanks for the game!

[S_S 2022-02-18 at 10 07 42 PM](https://user-images.githubusercontent.com/91811275/154787127-fc4578b8-4de3-4e0c-8187-440d63568d41.png)
!

**Comment by lynn** [comment]
Thanks for reporting this!

TAKKY became valid when I merged in the word list from Wordle, because people kept telling me their Wordle openers weren't valid in _hello wordl_.

Even though I agree that the Wordle dictionary is way too lenient and has a lot of weird words in it, I don't really want to selectively filter words out of it.
